name: Test Requirements

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List everything in repo
        run: ls -R

      - name: List inside proba2/proba2
        run: ls -l
        working-directory: ./proba2/proba2

      - name: Show current working directory
        run: pwd

      - name: Try installing requirements
        run: pip install -r requirements.txt
        working-directory: ./proba2/proba2
