name: Update XML Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Изпълнение всеки ден в 00:00 UTC (03:00 българско време)
  workflow_dispatch:  # Позволява и ръчно стартиране

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run filstar_checker.py
        run: python filstar_checker.py
        env:
          GITHUB_ACTIONS: true

      - name: Run filstar_converter.py
        run: python filstar_converter.py
        env:
          GITHUB_ACTIONS: true

      - name: List generated files
        run: ls -lh

      - name: Commit and push generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.csv *.xml
          git commit -m "✅ Daily update: CSV and XML files [skip ci]" || echo "No changes to commit"
          git push
