name: Update XML Daily

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:    # manual trigger option

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed to push changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run filstar scripts
        run: |
          python filstar_checker.py
          python filstar_converter.py

      - name: List generated XML and CSV files
        run: ls -lh *.xml *.csv || echo "No XML or CSV files found"

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.xml *.csv
          git commit -m "Daily auto-update XML and CSV [skip ci]" || echo "No changes to commit"
          git push
